# -*- coding: utf-8 -*-
"""PSO TASK SCHEDULING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_vsl2mo4TCrhbNt05KU-7ncj4Lzkyh4
"""

import random

# Number of tasks and machines
tasks = [4, 2, 7, 3, 5]
machines = 2

particles = 5
iterations = 20

# Calculate fitness (makespan)
def fitness(schedule):
    load = [0] * machines

    for i in range(len(tasks)):
        machine = schedule[i]
        load[machine] += tasks[i]

    return max(load)


# Initialize particles
swarm = []

for i in range(particles):
    schedule = [random.randint(0, machines - 1) for _ in tasks]
    swarm.append(schedule)

# Personal best
pbest = [x[:] for x in swarm]
pbest_cost = [fitness(x) for x in swarm]

# Global best
best_index = pbest_cost.index(min(pbest_cost))
gbest = pbest[best_index][:]
gbest_cost = pbest_cost[best_index]


# PSO
for _ in range(iterations):

    for i in range(particles):

        # Move particle towards global best
        for j in range(len(tasks)):

            if random.random() < 0.5:
                swarm[i][j] = gbest[j]
            else:
                swarm[i][j] = random.randint(0, machines - 1)

        cost = fitness(swarm[i])

        # Update personal best
        if cost < pbest_cost[i]:
            pbest[i] = swarm[i][:]
            pbest_cost[i] = cost

        # Update global best
        if cost < gbest_cost:
            gbest = swarm[i][:]
            gbest_cost = cost


# Display result
print("Task Execution Times:", tasks)
print("\nBest Schedule:")

for i in range(len(tasks)):
    print("Task", i + 1, "-> Machine", gbest[i] + 1)

print("\nMinimum Makespan:", gbest_cost)